import { StyleSheet } from 'react-native';

import { ctaStyles } from '@/components/screen/ctaStyles';
import { surfaceCardStyles } from '@/components/screen/surfaceCardStyles';
import { tabScreenStyles } from '@/components/screen/tabScreenStyles';
import { palette, radius, screenContentGutter, typography } from '@/constants/theme';

/** Shared chrome for tab screens — headers aligned via `TabScreenHeader`. */
export const youScreenStyles = StyleSheet.create({
  surface: {
    flex: 1,
  },
  scroll: {
    flex: 1,
  },
  headerRow: tabScreenStyles.headerRow,
  headerCopy: tabScreenStyles.headerCopy,
  title: tabScreenStyles.title,
  subtitle: tabScreenStyles.subtitle,
  iconCircle: tabScreenStyles.iconCircle,
  sectionWrap: {
    paddingHorizontal: screenContentGutter,
    gap: 12,
    marginBottom: 12,
  },
  sectionLabel: {
    ...typography.caption,
    fontWeight: '700',
    letterSpacing: 0.3,
    textTransform: 'uppercase',
    marginBottom: 2,
  },
  feedCard: {
    ...surfaceCardStyles.grouped,
    borderRadius: 18,
  },
  primaryBtn: {
    alignSelf: 'flex-start',
    borderRadius: radius.pill,
    paddingHorizontal: 16,
    paddingVertical: 11,
    marginTop: 2,
  },
  primaryBtnText: {
    ...ctaStyles.primaryLabel,
  },
  focusCard: {
    ...surfaceCardStyles.focus,
  },
  focusTitle: {
    ...typography.title,
    fontWeight: '800',
    letterSpacing: -0.3,
  },
  focusBody: {
    ...typography.compact,
    lineHeight: 21,
  },
  focusPrimaryBtn: {
    ...ctaStyles.primary,
    marginTop: 2,
  },
  focusPrimaryBtnText: {
    ...ctaStyles.primaryLabel,
  },
  focusLensBlock: {
    gap: 8,
    paddingTop: 12,
    borderTopWidth: StyleSheet.hairlineWidth,
  },
  focusMetricsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingTop: 10,
    borderTopWidth: StyleSheet.hairlineWidth,
    flexWrap: 'wrap',
  },
  focusMetricLabel: {
    ...typography.caption,
    fontWeight: '600',
  },
  focusMetricValue: {
    ...typography.compact,
    fontWeight: '700',
    fontVariant: ['tabular-nums'],
  },
  focusMetricDot: {
    ...typography.caption,
    fontWeight: '600',
  },
  focusRewardsTap: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 2,
    marginLeft: 'auto',
  },
  threadsTitle: {
    ...typography.titleSm,
    fontWeight: '700',
    letterSpacing: -0.2,
  },
  ghostBtn: {
    alignSelf: 'flex-start',
    borderRadius: radius.pill,
    borderWidth: StyleSheet.hairlineWidth,
    paddingHorizontal: 14,
    paddingVertical: 9,
  },
  ghostBtnText: {
    ...typography.compact,
    fontWeight: '700',
  },
  footerNote: {
    ...typography.caption,
    lineHeight: 18,
    textAlign: 'center',
    paddingHorizontal: screenContentGutter + 8,
    marginTop: 4,
  },
  snapshotCard: {
    flexDirection: 'row',
    alignItems: 'stretch',
    paddingVertical: 12,
    gap: 0,
  },
  statCell: {
    flex: 1,
    minWidth: 0,
    gap: 2,
    paddingHorizontal: 4,
  },
  snapshotDivider: {
    width: 1,
    alignSelf: 'stretch',
    marginVertical: 4,
  },
  confidenceTrack: {
    height: 4,
    borderRadius: 999,
    overflow: 'hidden',
  },
  confidenceFill: {
    height: '100%',
    borderRadius: 999,
  },
  cardTitle: {
    ...typography.titleSm,
    fontWeight: '700',
  },
  cardBody: {
    ...typography.compact,
    lineHeight: 20,
  },
  patternChip: {
    borderRadius: radius.pill,
    borderWidth: StyleSheet.hairlineWidth,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  patternChipText: {
    ...typography.caption,
    fontWeight: '600',
  },
  lensHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  patternRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  sectionHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
    marginBottom: 2,
  },
  postList: {
    gap: 0,
    marginHorizontal: -2,
  },
  postRow: {
    gap: 6,
    paddingVertical: 10,
  },
  postRowPressed: {
    opacity: 0.88,
  },
  postTop: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  categoryPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    borderRadius: radius.pill,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  categoryText: {
    ...typography.caption,
    fontWeight: '700',
  },
  postQuestion: {
    ...typography.bodySm,
    fontWeight: '700',
    lineHeight: 20,
  },
  postFoot: {
    ...typography.caption,
  },
  activityFilterContent: {
    gap: 10,
    paddingBottom: 8,
  },
  activityFilterChip: {
    borderRadius: radius.pill,
    paddingHorizontal: 14,
    paddingVertical: 8,
  },
  activityFilterLabel: {
    ...typography.compact,
    fontWeight: '600',
  },
  activityFilterLabelActive: {
    color: '#ffffff',
    fontWeight: '700',
  },
  profileTitleRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 12,
  },
  gearBtn: {
    width: 40,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 4,
  },
  sectionTitlePress: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 4,
    marginBottom: 8,
  },
  insightRow: {
    flexDirection: 'row',
    alignItems: 'stretch',
    gap: 8,
    paddingHorizontal: screenContentGutter,
    marginBottom: 12,
  },
  insightColumn: {
    flex: 1,
    minWidth: 0,
  },
  insightColumnDna: {
    flex: 1,
    minWidth: 0,
  },
  insightColumnRecent: {
    flex: 1,
    minWidth: 0,
  },
  insightCardShell: {
    flex: 1,
    ...surfaceCardStyles.grouped,
    borderRadius: radius.hero,
  },
  insightCardColumn: {
    justifyContent: 'space-between',
  },
  insightCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 4,
    marginBottom: 6,
  },
  sectionHeaderCopy: {
    flex: 1,
    minWidth: 0,
    gap: 2,
  },
  cardListFooterBtn: {
    marginTop: 12,
    marginBottom: 2,
    alignSelf: 'stretch',
    alignItems: 'center',
  },
  insightCardTitle: {
    ...typography.subhead,
    fontSize: 13,
    fontWeight: '700',
    lineHeight: 16,
    flex: 1,
    letterSpacing: -0.2,
  },
  insightListBody: {
    flex: 1,
    gap: 0,
  },
  insightFeedCard: {
    ...surfaceCardStyles.insight,
  },
  dnaSummaryBoxCompact: {
    borderRadius: 10,
    paddingHorizontal: 8,
    paddingVertical: 8,
    gap: 6,
  },
  dnaSummaryCompact: {
    ...typography.caption,
    lineHeight: 16,
    fontStyle: 'italic',
  },
  dnaSummaryText: {
    ...typography.compact,
    fontSize: 13,
    lineHeight: 18,
    fontStyle: 'italic',
  },
  dnaTeaserBox: {
    alignItems: 'center',
    paddingVertical: 12,
    gap: 4,
  },
  dnaTeaserTitle: {
    ...typography.titleSm,
    fontWeight: '700',
  },
  dnaTeaserBody: {
    ...typography.compact,
    lineHeight: 20,
    textAlign: 'center',
  },
  recentEmptyState: {
    paddingVertical: 12,
    paddingHorizontal: 4,
  },
  identityRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingHorizontal: screenContentGutter,
    marginBottom: 12,
  },
  identityMetaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
  },
  quoteCard: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 4,
    borderRadius: 16,
    paddingHorizontal: 14,
    paddingVertical: 14,
    marginHorizontal: screenContentGutter,
    marginBottom: 14,
  },
  quoteMark: {
    fontSize: 32,
    lineHeight: 32,
    fontWeight: '700',
    marginTop: -4,
  },
  quoteCardText: {
    ...typography.compact,
    lineHeight: 21,
    flex: 1,
    fontStyle: 'italic',
    paddingTop: 4,
  },
  statsRowGrid: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
    marginBottom: 14,
  },
  statIconWrap: {
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  statMiniTop: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  statMiniCard: {
    flex: 1,
    minWidth: 0,
    borderRadius: 16,
    borderWidth: StyleSheet.hairlineWidth,
    paddingHorizontal: 12,
    paddingVertical: 12,
    gap: 4,
    shadowColor: '#0b1224',
    shadowOpacity: 0.05,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 2 },
    elevation: 1,
  },
  statMiniValue: {
    ...typography.title,
    fontSize: 18,
    lineHeight: 22,
    fontWeight: '800',
    fontVariant: ['tabular-nums'],
    flexShrink: 1,
  },
  statMiniLabel: {
    ...typography.micro,
    fontWeight: '600',
    lineHeight: 14,
  },
  statMiniHint: {
    ...typography.micro,
    fontWeight: '600',
    lineHeight: 14,
  },
  growthCardShell: {
    gap: 8,
    paddingBottom: 16,
  },
  growthColumnsRow: {
    flexDirection: 'row',
    alignItems: 'stretch',
    paddingTop: 2,
  },
  growthColumn: {
    flex: 1,
    minWidth: 0,
    alignItems: 'center',
    paddingHorizontal: 6,
    paddingVertical: 6,
    gap: 8,
  },
  growthColumnDivider: {
    width: StyleSheet.hairlineWidth,
    marginVertical: 18,
    alignSelf: 'stretch',
  },
  growthIconWrap: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  growthCardTitle: {
    ...typography.caption,
    fontWeight: '700',
    textAlign: 'center',
  },
  growthCardBody: {
    ...typography.caption,
    lineHeight: 16,
    textAlign: 'center',
    fontWeight: '500',
  },
  recentTitleRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 6,
  },
  recentDecisionRowLayout: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  recentIconWrap: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
  },
  recentIconWrapCompact: {
    width: 30,
    height: 30,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  recentDecisionCopy: {
    flex: 1,
    minWidth: 0,
    gap: 2,
  },
  recentDecisionTitle: {
    ...typography.bodySm,
    fontWeight: '700',
    lineHeight: 20,
  },
  recentDecisionTitleCompact: {
    ...typography.caption,
    fontWeight: '700',
  },
  postFootCompact: {
    ...typography.caption,
    lineHeight: 16,
  },
  statusPillInsight: {
    borderRadius: radius.pill,
    paddingHorizontal: 5,
    paddingVertical: 4,
    minWidth: 48,
    maxWidth: 56,
  },
  statusPillInsightText: {
    ...typography.caption,
    fontWeight: '700',
    textAlign: 'center',
  },
  startDecisionBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    borderWidth: StyleSheet.hairlineWidth,
    borderRadius: radius.pill,
    paddingHorizontal: 16,
    paddingVertical: 12,
    marginTop: 12,
  },
  startDecisionBtnText: {
    ...typography.compact,
    fontWeight: '700',
  },
  startDecisionBtnCompact: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
    borderWidth: StyleSheet.hairlineWidth,
    borderRadius: 12,
    paddingHorizontal: 10,
    paddingVertical: 10,
    marginTop: 10,
  },
  startDecisionBtnTextCompact: {
    ...typography.caption,
    fontWeight: '600',
  },
  identityCard: {
    gap: 12,
  },
  identityTop: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  profileAvatar: {
    width: 72,
    height: 72,
    borderRadius: 36,
    alignItems: 'center',
    justifyContent: 'center',
  },
  profileAvatarImage: {
    width: 80,
    height: 80,
    borderRadius: 40,
  },
  profileAvatarEmoji: {
    fontSize: 30,
  },
  identityCopy: {
    flex: 1,
    minWidth: 0,
    gap: 4,
  },
  identityNameRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    flexWrap: 'wrap',
  },
  identityName: {
    ...typography.titleSm,
    fontSize: 20,
    fontWeight: '800',
    letterSpacing: -0.3,
  },
  premiumPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
    borderRadius: radius.pill,
    paddingHorizontal: 8,
    paddingVertical: 3,
  },
  premiumPillText: {
    ...typography.caption,
    fontWeight: '800',
  },
  identityMeta: {
    ...typography.caption,
    fontWeight: '600',
  },
  identityQuote: {
    ...typography.compact,
    lineHeight: 21,
    fontStyle: 'italic',
  },
  statsGrid: {
    gap: 10,
  },
  statsGridRow: {
    flexDirection: 'row',
    gap: 10,
  },
  statTile: {
    flex: 1,
    borderRadius: 16,
    borderWidth: StyleSheet.hairlineWidth,
    paddingHorizontal: 12,
    paddingVertical: 12,
    gap: 2,
    minWidth: 0,
  },
  statTileLabel: {
    ...typography.caption,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.2,
  },
  statTileValue: {
    ...typography.title,
    fontSize: 24,
    lineHeight: 28,
    fontWeight: '800',
    fontVariant: ['tabular-nums'],
  },
  statTileHint: {
    ...typography.caption,
    lineHeight: 15,
  },
  dnaRadarWrap: {
    paddingTop: 4,
    paddingBottom: 2,
    overflow: 'visible',
  },
  dnaSummaryBox: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  recentDecisionRow: {
    gap: 4,
    paddingVertical: 10,
  },
  recentDecisionRowCompact: {
    paddingVertical: 9,
  },
  recentDecisionTop: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  statusPill: {
    borderRadius: radius.pill,
    paddingHorizontal: 8,
    paddingVertical: 3,
  },
  statusPillText: {
    ...typography.caption,
    fontWeight: '700',
  },
  patternTabRow: {
    flexDirection: 'row',
    gap: 6,
  },
  patternTab: {
    borderRadius: radius.pill,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  patternInsightRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
    paddingVertical: 10,
  },
  patternInsightIcon: {
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  settingsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingVertical: 12,
    paddingHorizontal: 2,
  },
  settingsIconWrap: {
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  quoteBanner: {
    borderRadius: 18,
    borderWidth: StyleSheet.hairlineWidth,
    paddingHorizontal: 16,
    paddingVertical: 18,
    gap: 6,
    marginHorizontal: screenContentGutter,
    marginTop: 4,
  },
  quoteBannerText: {
    ...typography.compact,
    lineHeight: 22,
    fontStyle: 'italic',
    textAlign: 'center',
  },
  quoteBannerAttrib: {
    ...typography.caption,
    textAlign: 'center',
    fontWeight: '600',
  },
});
