import { Platform, StyleSheet } from 'react-native';

import { palette, profileNeutralStroke, profileTypography, radius, spacing, typography } from '@/constants/theme';

/** Shared Discuss / Review-draft card chrome — keep in sync with DiscussExpanded. */
export const discussCardStyles = StyleSheet.create({
  wrap: {
    alignSelf: 'stretch',
    width: '100%',
  },
  summarySection: {
    marginTop: 18,
    gap: 14,
  },
  aiDecisionCard: {
    gap: 10,
    paddingVertical: 16,
    paddingHorizontal: 18,
    borderRadius: 26,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: `${palette.neonPink}28`,
    borderLeftWidth: 4,
    borderLeftColor: '#0f172a',
    backgroundColor: 'rgba(255,253,255,0.92)',
    ...Platform.select({
      ios: {
        shadowColor: palette.heroInk,
        shadowOpacity: 0.08,
        shadowRadius: 14,
        shadowOffset: { width: 0, height: 4 },
      },
      android: { elevation: 2 },
      default: {},
    }),
  },
  aiDecisionHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    flexWrap: 'wrap',
  },
  aiDecisionBadge: {
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 3,
    backgroundColor: '#0f172a',
  },
  aiDecisionBadgeText: {
    fontSize: 9,
    lineHeight: 12,
    fontWeight: '800',
    letterSpacing: 0.6,
    color: palette.white,
  },
  aiDecisionPick: {
    ...typography.caption,
    color: profileTypography.subdued,
    fontWeight: '600',
    letterSpacing: 0.12,
    flex: 1,
  },
  aiDecisionHeadline: {
    ...typography.h2,
    color: profileTypography.ink,
    fontWeight: '700',
    letterSpacing: -0.35,
    lineHeight: 24,
    fontSize: 17,
  },
  aiDecisionReason: {
    ...typography.compact,
    color: profileTypography.body,
    lineHeight: 21,
    fontWeight: '500',
  },
  aiSignalsSection: {
    gap: 10,
    marginTop: 2,
    paddingTop: 12,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: profileNeutralStroke(0.08),
  },
  aiSignalsEyebrow: {
    ...typography.caption,
    color: profileTypography.subdued,
    fontWeight: '800',
    letterSpacing: 0.35,
    textTransform: 'uppercase',
  },
  aiSignalsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  aiSignalTile: {
    flexBasis: '47%',
    flexGrow: 1,
    minWidth: 132,
    gap: 5,
    paddingHorizontal: 12,
    paddingVertical: 11,
    borderRadius: radius.md,
    backgroundColor: 'rgba(255,255,255,0.84)',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: profileNeutralStroke(0.08),
  },
  aiSignalLabel: {
    ...typography.caption,
    color: profileTypography.subdued,
    fontWeight: '800',
    letterSpacing: 0.3,
    textTransform: 'uppercase',
  },
  aiSignalValue: {
    ...typography.compact,
    color: profileTypography.body,
    lineHeight: 19,
    fontWeight: '600',
  },
  aiReactionRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginTop: 2,
  },
  aiReactionPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 9,
    borderRadius: 999,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: profileNeutralStroke(0.1),
    backgroundColor: 'rgba(255,255,255,0.82)',
  },
  aiReactionLabel: {
    ...typography.caption,
    color: profileTypography.body,
    fontWeight: '800',
  },
  communitySectionHeader: {
    marginTop: 18,
    gap: 5,
    paddingHorizontal: 2,
  },
  communitySectionEyebrow: {
    ...typography.caption,
    color: profileTypography.subdued,
    fontWeight: '800',
    letterSpacing: 0.45,
    textTransform: 'uppercase',
  },
  communitySectionTitle: {
    ...typography.h2,
    color: profileTypography.ink,
    fontWeight: '800',
    letterSpacing: -0.4,
  },
  communitySectionBody: {
    ...typography.compact,
    color: profileTypography.emphasis,
    lineHeight: 20,
    fontWeight: '500',
  },
  communitySectionMeta: {
    ...typography.caption,
    color: profileTypography.subdued,
    fontWeight: '700',
  },
  filterRail: {
    marginTop: 14,
    marginBottom: 2,
    flexGrow: 0,
  },
  filterRailContent: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 6,
    paddingRight: spacing.sm,
    gap: 0,
  },
  filterChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 14,
    paddingVertical: 9,
    marginRight: 8,
    borderRadius: radius.pill,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: profileNeutralStroke(0.09),
    backgroundColor: 'rgba(255,255,255,0.82)',
    maxWidth: 220,
    ...Platform.select({
      ios: {
        shadowColor: '#0b1224',
        shadowOpacity: 0.035,
        shadowRadius: 5,
        shadowOffset: { width: 0, height: 1 },
      },
      android: { elevation: 1 },
      default: {},
    }),
  },
  filterChipOn: {
    borderColor: 'rgba(79,118,194,0.5)',
    backgroundColor: 'rgba(227,236,255,0.95)',
  },
  filterChipText: {
    ...typography.compact,
    color: profileTypography.emphasis,
    fontWeight: '600',
    flexShrink: 1,
  },
  filterChipTextOn: {
    color: palette.accent,
  },
  filterStripe: {
    width: 4,
    height: 16,
    borderRadius: 2,
    marginRight: 2,
    flexShrink: 0,
  },
  threadList: {
    gap: 10,
    marginTop: 14,
  },
  threadRow: {
    paddingVertical: 14,
    paddingHorizontal: 14,
    paddingLeft: 15,
    borderLeftWidth: 4,
    borderRadius: radius.lg,
    backgroundColor: 'rgba(255,255,255,0.88)',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: profileNeutralStroke(0.06),
    ...Platform.select({
      ios: {
        shadowColor: profileTypography.ink,
        shadowOpacity: 0.04,
        shadowRadius: 12,
        shadowOffset: { width: 0, height: 3 },
      },
      android: { elevation: 2 },
      default: {},
    }),
  },
  threadRowTop: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    flexWrap: 'wrap',
    marginBottom: 6,
  },
  threadEmoji: {
    fontSize: 16,
  },
  threadAuthor: {
    fontWeight: '700',
    color: profileTypography.body,
    flexShrink: 1,
  },
  threadTime: {
    ...typography.caption,
    color: profileTypography.subdued,
    marginLeft: 4,
    fontWeight: '600',
  },
  draftPill: {
    marginLeft: 'auto',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 999,
    backgroundColor: 'rgba(79,118,194,0.12)',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(79,118,194,0.28)',
  },
  draftPillText: {
    fontSize: 10,
    lineHeight: 13,
    fontWeight: '800',
    color: palette.accent,
    letterSpacing: 0.2,
    textTransform: 'uppercase',
  },
  threadBody: {
    ...typography.body,
    color: profileTypography.body,
    fontWeight: '400',
    lineHeight: 23,
    letterSpacing: -0.1,
  },
  composerSheet: {
    marginTop: 18,
    gap: 10,
    padding: spacing.md,
    borderRadius: radius.lg,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: profileNeutralStroke(0.08),
    backgroundColor: 'rgba(255,255,255,0.9)',
    ...Platform.select({
      ios: {
        shadowColor: '#0b1224',
        shadowOpacity: 0.04,
        shadowRadius: 10,
        shadowOffset: { width: 0, height: 3 },
      },
      android: { elevation: 2 },
      default: {},
    }),
  },
  composerEyebrow: {
    ...typography.caption,
    color: profileTypography.subdued,
    fontWeight: '800',
    letterSpacing: 0.35,
    textTransform: 'uppercase',
  },
  composerInput: {
    ...typography.body,
    color: profileTypography.body,
    lineHeight: 23,
    minHeight: 88,
    maxHeight: 160,
    textAlignVertical: 'top',
  },
  addPreviewBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    alignSelf: 'flex-start',
    marginTop: 8,
    paddingVertical: 8,
    paddingHorizontal: 2,
  },
  addPreviewText: {
    ...typography.compact,
    color: palette.accent,
    fontWeight: '700',
  },
  editableField: {
    padding: 0,
    margin: 0,
    borderWidth: 0,
    backgroundColor: 'transparent',
  },
});
