import type { ExploreCard } from '@shouldi/contracts';

export const seededExploreCards: ExploreCard[] = [
  {
    id: 'seed-money-1',
    category: 'money',
    status: 'resolved',
    author: { id: 'u-alex', name: 'Alex', avatarEmoji: '🧠' },
    question: 'Should I take a higher-paying role at a shaky company?',
    options: [
      { id: 'take-pay', label: 'Take higher pay' },
      { id: 'stay-stable', label: 'Choose stability' },
      { id: 'negotiate', label: 'Negotiate then decide' },
    ],
    distribution: [
      { optionId: 'take-pay', votes: 132 },
      { optionId: 'stay-stable', votes: 187 },
      { optionId: 'negotiate', votes: 64 },
    ],
    discussionPreview: [
      'Stability matters if your runway is under 6 months.',
      'Take pay if skills compounding is still strong.',
      'Negotiate severance terms before signing.',
    ],
    rewardPoints: 20,
    followedByMe: true,
    myVoteOptionId: 'stay-stable',
    winningOptionId: 'stay-stable',
    rewardEligibleOptionId: 'stay-stable',
    notifiedOnOutcome: true,
    hook: 'Took the higher paycheck at a shrinking company.',
    tension: 'I ignored warning signs because the salary felt like “finally making it”.',
    outcome: 'A layoff came 14 months later. The cash cushion helped, but the reset cost time and confidence.',
    takeaway: 'If pay is solving fear, quantify runway and revisit offer trade-offs—not just headline comp.',
    provenance: 'community_story',
    matchHint: 'Popular with early-career “should I chase title vs stability?” readers.',
  },
  {
    id: 'seed-career-1',
    category: 'career',
    status: 'open',
    author: { id: 'u-maya', name: 'Maya', avatarEmoji: '🎯' },
    question: 'Should I move into management now or stay IC longer?',
    options: [
      { id: 'mgmt-now', label: 'Move to management' },
      { id: 'stay-ic', label: 'Stay IC' },
      { id: 'trial-lead', label: 'Trial leadership first' },
    ],
    distribution: [
      { optionId: 'mgmt-now', votes: 102 },
      { optionId: 'stay-ic', votes: 141 },
      { optionId: 'trial-lead', votes: 196 },
    ],
    discussionPreview: [
      'Try leading one project before changing role.',
      'IC depth can still compound your long-term leverage.',
      'Management is mostly communication and context switching.',
    ],
    rewardPoints: 15,
    followedByMe: false,
    notifiedOnOutcome: false,
    hook: 'Said yes to leadership before I liked managing.',
    tension: 'I confused promotion with readiness. The calendar filled with coordination, not craft.',
    provenance: 'curated_digest',
  },
  {
    id: 'seed-relationship-1',
    category: 'relationship',
    status: 'resolved',
    author: { id: 'u-jordan', name: 'Jordan', avatarEmoji: '💬' },
    question: 'Should I address conflict now or wait for calmer timing?',
    options: [
      { id: 'address-now', label: 'Address now' },
      { id: 'wait', label: 'Wait for calm moment' },
    ],
    distribution: [
      { optionId: 'address-now', votes: 244 },
      { optionId: 'wait', votes: 89 },
    ],
    discussionPreview: [
      'Short check-ins beat one huge confrontation.',
      'Waiting too long usually amplifies assumptions.',
    ],
    rewardPoints: 12,
    followedByMe: true,
    myVoteOptionId: 'address-now',
    winningOptionId: 'address-now',
    rewardEligibleOptionId: 'address-now',
    notifiedOnOutcome: true,
    hook: 'Stayed silent to keep the peace—until I couldn’t.',
    tension: 'Avoiding conflict shortened arguments but stretched resentment.',
    outcome: 'A structured conversation broke the pattern.',
    takeaway: 'Name needs early with a cooldown rule: short check-ins beat surprise ultimatums.',
    provenance: 'community_story',
  },
  {
    id: 'seed-life-1',
    category: 'life',
    status: 'open',
    author: { id: 'u-rin', name: 'Rin', avatarEmoji: '🧭' },
    question: 'Should I relocate now or delay until work is more stable?',
    options: [
      { id: 'move-now', label: 'Relocate now' },
      { id: 'delay', label: 'Delay relocation' },
      { id: 'pilot', label: 'Run a 2-month pilot' },
    ],
    distribution: [
      { optionId: 'move-now', votes: 118 },
      { optionId: 'delay', votes: 97 },
      { optionId: 'pilot', votes: 173 },
    ],
    discussionPreview: [
      'Pilot runs reduce regret on reversible choices.',
      'Big moves are usually logistics, not identity shifts.',
      'Test costs before committing fully.',
    ],
    rewardPoints: 18,
    followedByMe: false,
    notifiedOnOutcome: false,
    hook: 'Deferred a relocation for “perfect timing”.',
    tension: 'I waited until everything lined up professionally. Life doesn’t cooperate with that plan.',
    provenance: 'ai_framework',
  },
];
