import type { ExploreCard } from '@shouldi/contracts';

export const seededExploreCards: ExploreCard[] = [
  {
    id: 'seed-money-1',
    category: 'money',
    status: 'resolved',
    author: { id: 'u-alex', name: 'Alex', avatarEmoji: '🧠' },
    question: 'Should I take a higher-paying role at a shaky company?',
    options: [
      { id: 'take-pay', label: 'Take higher pay' },
      { id: 'stay-stable', label: 'Choose stability' },
      { id: 'negotiate', label: 'Negotiate then decide' },
    ],
    distribution: [
      { optionId: 'take-pay', votes: 132 },
      { optionId: 'stay-stable', votes: 187 },
      { optionId: 'negotiate', votes: 64 },
    ],
    discussionPreview: [
      'Stability matters if your runway is under 6 months.',
      'Take pay if skills compounding is still strong.',
      'Negotiate severance terms before signing.',
    ],
    rewardPoints: 20,
    savedByMe: false,
    followedByMe: true,
    myVoteOptionId: 'stay-stable',
    winningOptionId: 'stay-stable',
    rewardEligibleOptionId: 'stay-stable',
    notifiedOnOutcome: true,
    hook: 'Took the higher paycheck at a shrinking company.',
    tension: 'I ignored warning signs because the salary felt like “finally making it”.',
    outcome: 'A layoff came 14 months later. The cash cushion helped, but the reset cost time and confidence.',
    takeaway: 'If pay is solving fear, quantify runway and revisit offer trade-offs—not just headline comp.',
    provenance: 'community_story',
    matchHint: 'Popular with early-career “should I chase title vs stability?” readers.',
    aiSuggestedOptionId: 'negotiate',
    aiSuggestionNote: 'Model runway and downside before choosing pay vs stability — negotiate terms first.',
  },
  {
    id: 'seed-career-1',
    category: 'career',
    status: 'open',
    author: { id: 'u-maya', name: 'Maya', avatarEmoji: '🎯' },
    question: 'Should I move into management now or stay IC longer?',
    options: [
      { id: 'mgmt-now', label: 'Move to management' },
      { id: 'stay-ic', label: 'Stay IC' },
      { id: 'trial-lead', label: 'Trial leadership first' },
    ],
    distribution: [
      { optionId: 'mgmt-now', votes: 102 },
      { optionId: 'stay-ic', votes: 141 },
      { optionId: 'trial-lead', votes: 196 },
    ],
    discussionPreview: [
      'Try leading one project before changing role.',
      'IC depth can still compound your long-term leverage.',
      'Management is mostly communication and context switching.',
    ],
    rewardPoints: 15,
    savedByMe: false,
    followedByMe: false,
    notifiedOnOutcome: false,
    hook: 'Said yes to leadership before I liked managing.',
    tension:
      'The role shifted faster into stakeholder sync and planning than deeper IC builds—the trade-off was easy to underestimate up front.',
    provenance: 'curated_digest',
    aiSuggestedOptionId: 'trial-lead',
    aiSuggestionNote: 'A bounded leadership trial lowers regret if IC craft still anchors your identity.',
  },
  {
    id: 'seed-relationship-1',
    category: 'relationship',
    status: 'resolved',
    author: { id: 'u-jordan', name: 'Jordan', avatarEmoji: '💬' },
    question: 'Should I address conflict now or wait for calmer timing?',
    options: [
      { id: 'address-now', label: 'Address now' },
      { id: 'wait', label: 'Wait for calm moment' },
    ],
    distribution: [
      { optionId: 'address-now', votes: 244 },
      { optionId: 'wait', votes: 89 },
    ],
    discussionPreview: [
      'Short check-ins beat one huge confrontation.',
      'Waiting too long usually amplifies assumptions.',
    ],
    rewardPoints: 12,
    savedByMe: false,
    followedByMe: true,
    myVoteOptionId: 'address-now',
    winningOptionId: 'address-now',
    rewardEligibleOptionId: 'address-now',
    notifiedOnOutcome: true,
    hook: 'Stayed silent to keep the peace—until I couldn’t.',
    tension: 'Avoiding conflict shortened arguments but stretched resentment.',
    outcome: 'A structured conversation broke the pattern.',
    takeaway: 'Name needs early with a cooldown rule: short check-ins beat surprise ultimatums.',
    provenance: 'community_story',
    aiSuggestedOptionId: 'wait',
    aiSuggestionNote: 'If either of you is flooded, a short pause with a calendar check-in often lands better than debating in the spillover moment.',
  },
  {
    id: 'seed-life-1',
    category: 'life',
    status: 'open',
    author: { id: 'u-rin', name: 'Rin', avatarEmoji: '🧭' },
    question: 'Should I relocate now or delay until work is more stable?',
    options: [
      { id: 'move-now', label: 'Relocate now' },
      { id: 'delay', label: 'Delay relocation' },
      { id: 'pilot', label: 'Run a 2-month pilot' },
    ],
    distribution: [
      { optionId: 'move-now', votes: 118 },
      { optionId: 'delay', votes: 97 },
      { optionId: 'pilot', votes: 173 },
    ],
    discussionPreview: [
      'Pilot runs reduce regret on reversible choices.',
      'Big moves are usually logistics, not identity shifts.',
      'Test costs before committing fully.',
    ],
    rewardPoints: 18,
    savedByMe: false,
    followedByMe: false,
    notifiedOnOutcome: false,
    hook: 'Deferred a relocation until work felt “stable.”',
    tension:
      'Every time work quieted down, something else moved—lease end date, visa timeline, partner’s role. Waiting for full alignment meant waiting forever.',
    provenance: 'ai_framework',
    aiSuggestedOptionId: 'pilot',
    aiSuggestionNote: 'Reversible pilots surface hidden constraints before irreversible leases and commutes.',
  },
  {
    id: 'seed-career-2',
    category: 'career',
    status: 'open',
    author: { id: 'u-sam', name: 'Sam', avatarEmoji: '🛠️' },
    question: 'Should I join an early-stage startup or stay at my mid-size company?',
    options: [
      { id: 'startup', label: 'Join startup' },
      { id: 'stay-mid', label: 'Stay mid-size' },
      { id: 'counter-offer', label: 'Use offer to negotiate' },
    ],
    distribution: [
      { optionId: 'startup', votes: 198 },
      { optionId: 'stay-mid', votes: 156 },
      { optionId: 'counter-offer', votes: 211 },
    ],
    discussionPreview: [
      'Clarify runway, cliff, and your role clarity with the founder.',
      'Mid-size equity is usually smaller but risk is thinner.',
      'Negotiation often wins even if you stay.',
    ],
    rewardPoints: 16,
    savedByMe: false,
    followedByMe: false,
    notifiedOnOutcome: false,
    hook: 'Two offers, two completely different timelines.',
    tension:
      'The startup upside story was exciting, but vesting pace and ambiguity on scope made it hard to compare to a predictable calendar at my current gig.',
    provenance: 'curated_digest',
    aiSuggestedOptionId: 'counter-offer',
    aiSuggestionNote:
      'Get the startup deck in writing, then negotiate from strength—either improves your BATNA before you leap.',
  },
  {
    id: 'seed-money-2',
    category: 'money',
    status: 'open',
    author: { id: 'u-ken', name: 'Ken', avatarEmoji: '📊' },
    question: 'Should I aggressively pay down student loans or prioritize investing first?',
    options: [
      { id: 'pay-loans', label: 'Prioritize payoff' },
      { id: 'invest', label: 'Invest simultaneously' },
      { id: 'split', label: 'Fixed split monthly' },
    ],
    distribution: [
      { optionId: 'pay-loans', votes: 401 },
      { optionId: 'invest', votes: 288 },
      { optionId: 'split', votes: 312 },
    ],
    discussionPreview: [
      'Match employer 401(k) free money before extras.',
      'High-rate debt often beats average market returns on paper.',
      'A modest emergency fund avoids new debt shocks.',
    ],
    rewardPoints: 14,
    savedByMe: false,
    followedByMe: false,
    notifiedOnOutcome: false,
    hook: 'The interest rate crossed the threshold where spreadsheets disagreed.',
    tension:
      'Psychological relief from wiping the loan fought with compounding timelines if markets stayed cooperative—neither spreadsheet captured sleep quality.',
    provenance: 'ai_framework',
    aiSuggestedOptionId: 'split',
    aiSuggestionNote: 'Hybrid plans often survive behavior better than extremes—automate savings and payoff in one cron.',
  },
  {
    id: 'seed-relationship-2',
    category: 'relationship',
    status: 'open',
    author: { id: 'u-eli', name: 'Eli', avatarEmoji: '🫶' },
    question: 'Should I set firmer boundaries with a friend who vents constantly?',
    options: [
      { id: 'direct', label: 'Be direct' },
      { id: 'gentle-limit', label: 'Gently limit bandwidth' },
      { id: 'distance', label: 'Create distance' },
    ],
    distribution: [
      { optionId: 'direct', votes: 91 },
      { optionId: 'gentle-limit', votes: 402 },
      { optionId: 'distance', votes: 67 },
    ],
    discussionPreview: [
      'Naming capacity (“I’ve got 10 min”) often lands better than vanishing.',
      'You’re not their therapist—even good friends need guardrails.',
      'Distance protects the friendship sometimes.',
    ],
    rewardPoints: 11,
    savedByMe: false,
    followedByMe: false,
    notifiedOnOutcome: false,
    hook: 'Every hangout turned into crisis mode—and I hadn’t slept.',
    tension:
      'I wanted to be supportive without becoming the unpaid emotional default, but bluntness risked sounding cold when they were already stretched.',
    provenance: 'community_story',
    matchHint: 'Common with carers and people-first personalities.',
    aiSuggestedOptionId: 'gentle-limit',
    aiSuggestionNote: 'Script a kind limit with a reschedule anchor—signals care without infinite availability.',
  },
  {
    id: 'seed-life-2',
    category: 'life',
    status: 'resolved',
    author: { id: 'u-nora', name: 'Nora', avatarEmoji: '🌿' },
    question: 'Should I take three months unpaid to reset burnout or slog through?',
    options: [
      { id: 'leave-now', label: 'Leave for three months' },
      { id: 'keep-going', label: 'Stay and patch' },
    ],
    distribution: [
      { optionId: 'leave-now', votes: 189 },
      { optionId: 'keep-going', votes: 76 },
    ],
    discussionPreview: [
      'Map minimum burn and cobra before you resign.',
      'Sometimes slogging keeps the burnout loop alive.',
      'Short breaks can unblock therapy and exercise habits.',
    ],
    rewardPoints: 22,
    savedByMe: false,
    followedByMe: false,
    myVoteOptionId: 'leave-now',
    winningOptionId: 'leave-now',
    rewardEligibleOptionId: 'leave-now',
    notifiedOnOutcome: true,
    hook: 'I framed “selfish” versus “preventing a bigger crash”.',
    tension:
      'Leaving felt irresponsible on spreadsheet day; staying felt irresponsible on symptom day—they never lined up in the same week.',
    outcome: 'A lean three months slowed the spiral; returning part-time lengthened runway without pretending I was healed.',
    takeaway: 'If rest is medically obvious and financially barely possible, the third path is reshape income, not heroic grind.',
    provenance: 'community_story',
    aiSuggestedOptionId: 'leave-now',
    aiSuggestionNote: 'If symptoms are escalating, timelines for recovery usually beat waiting for permission.',
  },
  {
    id: 'seed-career-3',
    category: 'career',
    status: 'resolved',
    author: { id: 'u-priya', name: 'Priya', avatarEmoji: '✨' },
    question: 'Should I specialize deep in one stack or aim for breadth across stacks?',
    options: [
      { id: 'deep', label: 'Go deep' },
      { id: 'broad', label: 'Stay broad' },
    ],
    distribution: [
      { optionId: 'deep', votes: 512 },
      { optionId: 'broad', votes: 203 },
    ],
    discussionPreview: [
      'Depth hires faster for senior scopes.',
      'Breadth survives role churn in volatile orgs.',
    ],
    rewardPoints: 13,
    savedByMe: false,
    followedByMe: false,
    myVoteOptionId: 'broad',
    winningOptionId: 'deep',
    rewardEligibleOptionId: 'deep',
    notifiedOnOutcome: true,
    hook: 'I kept collecting skills like Pokémon until interviews asked for proofs.',
    tension:
      'Breadth meant I understood systems end-to-end, but recruiters wanted one flagship specialty on the headline.',
    outcome: 'I doubled down on one pillar for two years—the next role unlocked when I could cite shipped metrics in that niche.',
    takeaway: 'T-shaped still wins—pick depth that matches roles you actually want, keep one adjacent lane sharp.',
    provenance: 'curated_digest',
    matchHint: 'Familiar to generalists leveling into staff.',
    aiSuggestedOptionId: 'deep',
    aiSuggestionNote: 'Depth stacks evidence faster for compensation jumps than another shallow badge.',
  },
  {
    id: 'seed-money-3',
    category: 'money',
    status: 'open',
    author: { id: 'u-tessa', name: 'Tessa', avatarEmoji: '🏠' },
    question: 'Should we buy a smaller condo now or keep renting until we save 20% down?',
    options: [
      { id: 'buy-smaller', label: 'Buy smaller now' },
      { id: 'rent-save', label: 'Rent and save to 20%' },
      { id: 'pause', label: 'Pause both for 6 months' },
    ],
    distribution: [
      { optionId: 'buy-smaller', votes: 124 },
      { optionId: 'rent-save', votes: 267 },
      { optionId: 'pause', votes: 88 },
    ],
    discussionPreview: [
      'Model payment + HOA + repairs vs renewal rent.',
      'PMI versus opportunity cost surprises people.',
      'Sometimes waiting is avoidance; sometimes it’s sane.',
    ],
    rewardPoints: 19,
    savedByMe: false,
    followedByMe: false,
    notifiedOnOutcome: false,
    hook: 'The rent hike letter arrived the same month as mortgage quotes.',
    tension:
      'Smaller footprint meant locking in predictable housing cost; renting meant flexibility but shrinking savings velocity as rent climbed.',
    provenance: 'community_story',
    aiSuggestedOptionId: 'rent-save',
    aiSuggestionNote: 'Stress-test affordability at +2% mortgage and a realistic repair kitty before “good enough”.',
  },
  {
    id: 'seed-relationship-3',
    category: 'relationship',
    status: 'open',
    author: { id: 'u-marcus', name: 'Marcus', avatarEmoji: '💛' },
    question: 'Should I tell them I’m not ready for labels yet or keep drifting?',
    options: [
      { id: 'name-it', label: 'Name uncertainty gently' },
      { id: 'keep-drift', label: 'Stay casual for now' },
      { id: 'step-back', label: 'Step back consciously' },
    ],
    distribution: [
      { optionId: 'name-it', votes: 233 },
      { optionId: 'keep-drift', votes: 98 },
      { optionId: 'step-back', votes: 45 },
    ],
    discussionPreview: [
      'Vague comfort often hides mismatched pacing.',
      'Kind clarity isn’t dumping—it’s sparing months of guessing.',
      'Drift without check-ins breeds resentment quietly.',
    ],
    rewardPoints: 12,
    savedByMe: false,
    followedByMe: false,
    notifiedOnOutcome: false,
    hook: 'We act like partners but dodge the vocabulary.',
    tension:
      'I didn’t want to pressure them—or sound avoidant—but the silence stretched into assumptions neither of us had signed.',
    provenance: 'community_story',
    aiSuggestedOptionId: 'name-it',
    aiSuggestionNote: 'Naming pace usually costs one awkward hour; avoiding it costs months of misplaced hope.',
  },
  {
    id: 'seed-life-3',
    category: 'life',
    status: 'open',
    author: { id: 'u-diego', name: 'Diego', avatarEmoji: '🎸' },
    question: 'Should I pick up a hobby that could become income or purely escapist fun?',
    options: [
      { id: 'monetize', label: 'Aim toward side income' },
      { id: 'pure-play', label: 'Keep it non-commercial' },
      { id: 'hybrid-six', label: 'Six-month experiment' },
    ],
    distribution: [
      { optionId: 'monetize', votes: 156 },
      { optionId: 'pure-play', votes: 201 },
      { optionId: 'hybrid-six', votes: 277 },
    ],
    discussionPreview: [
      'Revenue hobbies can silently drain joy if you obsess metrics.',
      'Pure play restores energy other work steals.',
      'Time-bound tests keep identity flexible.',
    ],
    rewardPoints: 10,
    savedByMe: false,
    followedByMe: false,
    notifiedOnOutcome: false,
    hook: 'I haven’t touched my instrument guilt-free since college.',
    tension:
      'Monetizing might justify the hours; keeping it sacred might be the whole point—and I feared choosing wrong would kill the outlet twice.',
    provenance: 'curated_digest',
    aiSuggestedOptionId: 'hybrid-six',
    aiSuggestionNote: 'Six months preserves both joy and curiosity before you marry the business model.',
  },
  {
    id: 'seed-career-4',
    category: 'career',
    status: 'open',
    author: { id: 'u-linh', name: 'Linh', avatarEmoji: '📣' },
    question: 'Should I push back on an unrealistic roadmap or swallow it silently?',
    options: [
      { id: 'push-back', label: 'Raise trade-offs visibly' },
      { id: 'document-only', label: 'Document privately' },
      { id: 'one-on-one', label: 'Calibrate one-on-one' },
    ],
    distribution: [
      { optionId: 'push-back', votes: 189 },
      { optionId: 'document-only', votes: 52 },
      { optionId: 'one-on-one', votes: 311 },
    ],
    discussionPreview: [
      'Group pushback needs allies and scope clarity.',
      'Private notes help if timelines blow up.',
      'Manager alignment before the room lowers heat.',
    ],
    rewardPoints: 14,
    savedByMe: false,
    followedByMe: false,
    notifiedOnOutcome: false,
    hook: 'The slide deck doubled scope without doubling people.',
    tension:
      'Speaking up risks “not a team player”; staying quiet risks owning a miss I already saw coming—with no receipts later.',
    provenance: 'ai_framework',
    aiSuggestedOptionId: 'one-on-one',
    aiSuggestionNote: 'A tight 1:1 with options—not venting—usually moves dates more than hallway heroics.',
  },
  {
    id: 'seed-money-4',
    category: 'money',
    status: 'open',
    author: { id: 'u-ina', name: 'Ina', avatarEmoji: '💳' },
    question: 'Should I refinance my loan now or wait for clearer rate signals?',
    options: [
      { id: 'refi-now', label: 'Refinance now' },
      { id: 'wait', label: 'Wait 90 days' },
      { id: 'run-numbers', label: 'Model break-even first' },
    ],
    distribution: [
      { optionId: 'refi-now', votes: 142 },
      { optionId: 'wait', votes: 88 },
      { optionId: 'run-numbers', votes: 264 },
    ],
    discussionPreview: [
      'Fees and resets eat blind optimism.',
      'Macro timing is louder than actionable for most borrowers.',
      'Break-even math beats headline rate.',
    ],
    rewardPoints: 15,
    savedByMe: false,
    followedByMe: false,
    notifiedOnOutcome: false,
    hook: 'The alert email said “lowest since…” again.',
    tension:
      'Rates could dip again—or rise while I noodle—and I didn’t know if my payoff timeline made the paperwork worth the adrenaline.',
    provenance: 'community_story',
    aiSuggestedOptionId: 'run-numbers',
    aiSuggestionNote: 'Breakeven months + realistic stay-in-home odds decide more than pundit guesses.',
  },
  {
    id: 'seed-life-4',
    category: 'life',
    status: 'open',
    author: { id: 'u-amelia', name: 'Amelia', avatarEmoji: '🐕' },
    question: 'Should we adopt the second pet we keep joking about?',
    options: [
      { id: 'yes-now', label: 'Yes, adopt' },
      { id: 'foster-first', label: 'Foster trial first' },
      { id: 'wait-year', label: 'Wait another year' },
    ],
    distribution: [
      { optionId: 'yes-now', votes: 67 },
      { optionId: 'foster-first', votes: 318 },
      { optionId: 'wait-year', votes: 112 },
    ],
    discussionPreview: [
      'Pets amplify joy and logistical load in equal spikes.',
      'Fostering de-risks chemistry with your rhythm.',
      'Travel and housing rules change more than cuddles imply.',
    ],
    rewardPoints: 11,
    savedByMe: false,
    followedByMe: false,
    notifiedOnOutcome: false,
    hook: 'The shelter photos got cruelly convincing after wine.',
    tension:
      'Commitment sounded romantic until we stared at crates, meds, vacation coverage, and the first dog’s jealousy face.',
    provenance: 'community_story',
    matchHint: 'Hits couples timing second pets.',
    aiSuggestedOptionId: 'foster-first',
    aiSuggestionNote: 'A bounded fostering stretch answers logistics before a decade contract.',
  },
  {
    id: 'seed-career-5',
    category: 'career',
    status: 'open',
    author: { id: 'u-omar', name: 'Omar', avatarEmoji: '🌍' },
    question: 'Should I accept overseas relocation for two years or ask for remote-only?',
    options: [
      { id: 'relocate', label: 'Relocate' },
      { id: 'remote-only', label: 'Stay remote-only' },
      { id: 'fly-monthly', label: 'Hybrid hub monthly' },
    ],
    distribution: [
      { optionId: 'relocate', votes: 94 },
      { optionId: 'remote-only', votes: 181 },
      { optionId: 'fly-monthly', votes: 255 },
    ],
    discussionPreview: [
      'Visa and tax timelines are not vibes.',
      'Remote carve-outs tighten when HQ wants presence.',
      'Monthly hub can split tax and burnout risks.',
    ],
    rewardPoints: 17,
    savedByMe: false,
    followedByMe: false,
    notifiedOnOutcome: false,
    hook: 'The map pin moved continents before daycare waitlists cleared.',
    tension:
      'The opportunity was flattering; uprooting spouse, language load, and school timing felt impossible to reconcile in one thumbs-up emoji.',
    provenance: 'curated_digest',
    aiSuggestedOptionId: 'fly-monthly',
    aiSuggestionNote: 'Hybrid presence often survives committee review longer than permanent “no”—and preserves family anchors.',
  },
];
